export const {
  FRONTEND_URL,
  FUSIONAUTH_HOST,
  FUSIONAUTH_API_KEY,
  FUSIONAUTH_TENANT_ID,
  FUSIONAUTH_CLIENT_ID,
  FUSIONAUTH_APPLICATION_ID,
  OAUTH_CONFIGURATION_CLIENT_SECRET,
} = process.env;
