export const AUTH_MODULE_OPTIONS = Symbol('AUTH_MODULE_OPTIONS');
export const AUTH_MODULE_FUSIONAUTH_CLIENT = Symbol(
  'AUTH_MODULE_FUSIONAUTH_CLIENT',
);
export const FUSIONAUTH_OAUTH_CALLBACK_URL = Symbol(
  'FUSIONAUTH_OAUTH_CALLBACK_URL',
);
