name: Composite setup e2e GitHub action
description: Setup docker

runs:
  using: "composite"
  steps:
    - name: Set up QEMU to add support for more platforms with QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Sets the BuildKit image to use for the container.
        # https://hub.docker.com/r/moby/buildkit/tags/
        driver-opts: image=moby/buildkit:v0.13.0
