#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! git diff --quiet ".github"; then
  echo "Running actionlint against github workflows..."
  actionlint
fi

if ! git diff --quiet "apps/backend"; then
  echo "Creating openApi.json and staging it..."
  nx openapi:generate backend
  git add apps/backend/openApi.json
fi

echo "Running lint-staged..."
npx lint-staged --relative

echo "Running affected tests..."
npx nx affected -t test
